paths:
  uploads: src/assets/
  uploads_use_relative_path: true
timezone: Etc/UTC
collections_config:
  pages:
    path: src/content/pages
    url: "/[full_slug|unless=href][href|if=href]/"
    name: Pages
    icon: article
    disable_add: false
    disable_add_folder: true
    disable_file_actions: true
    _enabled_editors:
      - visual
      - content
  reviews:
    path: src/content/pages/reviews
    name: Reviews
    icon: star
    disable_add: false
    disable_add_folder: true
    disable_file_actions: true
    _enabled_editors:
      - data
collection_groups:
  - heading: Content
    collections:
      - pages
      - menu
      - agenda
      - reviews
_structures:
  sections:
    id_key: block
    values:
      - label: Reviews
        value:
          block: reviews-3
        _inputs:
          refs:
            type: multiselect
            options:
              values: collections.reviews
              empty_type: array
_inputs:
  id:
    hidden: true
  class:
    hidden: true
  block:
    hidden: true
  size:
    hidden: true
  type:
    hidden: true
  variant:
    hidden: true
  background:
    hidden: true
  align:
    hidden: true
  glob:
    hidden: true
  icon:
    hidden: true
  refs:
    type: multiselect
    options:
      values: collections.pages
      empty_type: array
  ref:
    type: select
    options:
      values: collections.pages
      empty_type: string
  title:
    type: text
    options:
      empty_type: string
  description:
    type: textarea
    options:
      empty_type: string
  href:
    type: url
    label: Link
    options:
      empty_type: string
  tagline:
    type: text
    options:
      empty_type: string
  rating:
    type: range
    options:
      empty_type: number
      min: 0
      max: 5
      step: 0.1
  sections:
    type: array
    options:
      empty_type: array
      disable_add: true
      disable_remove: true
      disable_reorder: false
  list:
    type: array
    options:
      empty_type: array
      disable_add: false
      disable_remove: false
      disable_reorder: false
  list[*]:
    type: text
    options:
      empty_type: string
  socials:
    type: array
    options:
      empty_type: array
      disable_add: false
      disable_remove: false
      disable_reorder: false
  socials[*]:
    type: url
    options:
      empty_type: string
  links:
    type: array
    options:
      empty_type: array
      disable_add: false
      disable_remove: false
      disable_reorder: false
  buttons:
    type: array
    options:
      empty_type: array
      max_items: 2
      disable_add: false
      disable_remove: false
      disable_reorder: false
  link.href:
    type: url
    options:
      required: true
  link.text:
    type: text
    options:
      required: true
  seo.title:
    type: text
    options:
      required: true
  seo.description:
    type: textarea
    options:
      required: true
  src:
    type: image
    options:
      mime_type: image/webp
      resize_style: contain
      width: 2560
      height: 2560
  images:
    type: array
    options:
      empty_type: array
      disable_add: false
      disable_remove: false
      disable_reorder: false
  head:
    type: code
    options:
      min_visible_lines: 10
      max_visible_lines: 30
      tab_size: 2
      theme: monokai
      show_gutter: true
      syntax: html
  body:
    type: code
    options:
      min_visible_lines: 10
      max_visible_lines: 30
      tab_size: 2
      theme: monokai
      show_gutter: true
      syntax: html
  html:
    type: html
    label: Content
    options:
      allow_resize: true
      initial_height: 400
      allow_custom_markup: false
      remove_custom_markup: false
      blockquote: true
      bold: true
      bulletedlist: true
      format: p h1 h2 h3
      image_size_attributes: false
      italic: true
      underline: true
      undo: true
      empty_type: string
_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    format: p h1 h2 h3 h4 h5 h6
    italic: true
    link: true
    numberedlist: true
    redo: true
    table: false
    underline: true
    undo: true
    image: true
    height: 2560
    width: 2560
    resize_style: contain
    mime_type: image/webp
