paths:
  uploads: src/assets
collections_config:
  pages:
    path: src/content/pages
    url: "/[full_slug|unless=href][href|if=href]/"
    name: Pages
    icon: article
    disable_add: false
    disable_add_folder: true
    disable_file_actions: true
    _enabled_editors:
      - visual
      - content
  layouts:
    path: src/content/layouts
    name: Layouts
    icon: settings
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    _enabled_editors:
      - data
collection_groups:
  - heading: Content
    collections:
      - pages
      - layouts
timezone: Etc/UTC
_inputs:
  block:
    hidden: true
  size:
    hidden: true
  type:
    hidden: true
  variant:
    hidden: true
  background:
    hidden: true
  align:
    hidden: true
  glob:
    hidden: true
  published:
    type: date
    instance_value: NOW
    options:
      empty_type: string
      timezone: Etc/UTC
  title:
    type: text
    options:
      empty_type: string
  description:
    type: text
    options:
      empty_type: string
  href:
    type: url
    options:
      empty_type: string
  tagline:
    type: text
    options:
      empty_type: string
  icon:
    type: select
    options:
      empty_type: string
      values:
        - value: check
          label: Check
        - value: cross
          label: Cross
  paths:
    type: multiselect
    options:
      values: collections.pages
  rating:
    type: range
    options:
      empty_type: "null"
      min: 0
      max: 5
      step: 0.5
  blocks:
    type: array
    options:
      empty_type: array
      disable_add: false
      disable_remove: false
      disable_reorder: false
  list:
    type: array
    options:
      empty_type: array
      disable_add: false
      disable_remove: false
      disable_reorder: false
  list[*]:
    type: text
    options:
      empty_type: string
  socials:
    type: array
  socials[*]:
    type: url
    options:
      empty_type: string
  link:
    type: object
    options:
      structures: _structures.link
  buttons:
    type: array
    options:
      empty_type: array
      structures: _structures.link
      max_items: 2
      disable_add: false
      disable_remove: false
      disable_reorder: false
  link.href:
    type: url
    options:
      required: true
  link.text:
    type: text
    options:
      required: true
  seo:
    type: object
    options:
      subtype: object
      structures: _structures.seo
  src:
    type: image
    options:
      mime_type: image/webp
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      resize_style: contain
      width: 2560
      height: 2560
  images:
    type: array
    options:
      empty_type: array
      disable_add: false
      disable_remove: false
      disable_reorder: false
  images[*].src:
    type: image
    options:
      mime_type: image/webp
      accepts_mime_types: image/jpeg,image/jpg,image/png,image/webp
      resize_style: contain
      width: 2560
      height: 2560
  # Content
  head:
    type: code
    options:
      min_visible_lines: 10
      max_visible_lines: 30
      tab_size: 2
      theme: monokai
      show_gutter: true
      syntax: html
  body:
    type: code
    options:
      min_visible_lines: 10
      max_visible_lines: 30
      tab_size: 2
      theme: monokai
      show_gutter: true
      syntax: html
  css:
    type: code
    options:
      min_visible_lines: 10
      max_visible_lines: 30
      tab_size: 2
      theme: monokai
      show_gutter: true
      syntax: css
  # Richtext
  html:
    type: html
    label: Content
    options:
      allow_resize: true
      initial_height: 640
      allow_custom_markup: false
      remove_custom_markup: false
      blockquote: true
      bold: true
      bulletedlist: true
      format: p h1 h2 h3
      image_size_attributes: false
      italic: true
      underline: true
      undo: true
      empty_type: string

_editables:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    format: p h1 h2 h3 h4 h5 h6
    image: true
    italic: true
    link: true
    mime_type: image/webp
    numberedlist: true
    redo: true
    resize_style: contain
    table: false
    underline: true
    undo: true
    height: 2560
    width: 2560

_structures:
  link:
    values:
      - value:
          text: ""
          href: ""
  seo:
    values:
      - value:
          title: ""
          description: ""
